version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  newman:
    image: postman/newman:alpine
    depends_on:
      - api
    volumes:
      - D:\\github\\doc-composeNewmanExampleAPI\\collection\\etc\\newman:/etc/newman
    command: run /etc/newman/postman_collection.json